### ISSUE TITLE
ATmega128 const definitions not really const

### ISSUE THREAD

**Issue by tinyos-issues** [tinyos/tinyos-main#139]
_Original author: ondra.hosek@gmail.com (May 18, 2012 17:09:06)_

avr-gcc 4.7.0 complains that const_uint8_t etc. request data to be placed in a read-only segment in memory without that data being actually const.

The specific error message is:
error: variable 'McuSleepC__atm128PowerBits' must be const in order to be put into read-only section by means of '**attribute**((progmem))'

The attached patch fixes the problem.

_Original issue: http://code.google.com/p/tinyos-main/issues/detail?id=136_

**Comment by sp792** [comment]
Problem SOlved for me.... re-installing avr

sudo apt-get install avr-libc-tinyos
