### ISSUE TITLE
Current tinyos-tools breaks TinyOS 2.1.2 release   (was: Problem in compiling TOSSIM in TinyOS)

### ISSUE THREAD

**Issue by Harithfakhri** [tinyos/tinyos-main#289]
When I tried to compile TOSSIM by excuting following code:

$make micaz sim
I face a problem mentioned in http://stackoverflow.com/questions/23172776/tinyos-simulator-make-micaz-sim-missing-platform-file-tossim 

After implementation of troubleshooting steps provided by Appendix A in "http://tinyos.stanford.edu/tinyos-wiki/index.php/TOSSIM#Appendix_A:_Troubleshooting_TOSSIM_compilation" a new error appears to me 

/opt/tinyos-2.1.2/support/make/Makerules:180: **\* 

Usage:  make <target> <extras>
        make <target> help

```
    Valid targets: all clean epic eyesIFX eyesIFXv1 eyesIFXv2 intelmote2 iris mica2 mica2dot micaz mulle null sam3s_ek sam3u_ek shimmer shimmer2 shimmer2r span telos telosa telosb tinynode tmote ucmini z1
    Valid extras: appdoc blip cc2420x cc2420x_32khz coap cthreads docs dynthreads ident_flags nowiring rst safe savepp sim sim-fast sim-sf stack-check tframe threads tos_buildinfo tos_image tosboot tunit verbose wiring
```

 Welcome to the TinyOS make system!

 You must specify one of the valid targets and possibly some combination of
 the extra options.  Many targets have custom extras and extended help, so be
 sure to try "make <target> help" to learn of all the available features.

 Global extras:

   docs    : compile additional nescdoc documentation
   tinysec : compile with TinySec secure communication

ERROR, "mecaz sim ident_flags tos_image tosboot" does not specify a valid target. Stop.

**Comment by KosheilaPillay** [comment]
Hi, when I tried compiling TOSSIM for Blink application, I get the error stated below. I changed the .platform file to platform for micaz but the error still remains. Can anyone help me with this? I'm still very new to TinyOS. Thank you. :)

$ make micaz sim
mkdir -p simbuild/micaz
  placing object files in simbuild/micaz
  writing XML schema to app.xml
  compiling BlinkAppC to object file sim.o
ncc -c -DUSE_DL_IMPORT -fpic  -o simbuild/micaz/sim.o -g -O0 -tossim -fnesc-nido                                                                                                                                                 -tosnodes=1000 -fnesc-simulate -fnesc-nido-motenumber=sim_node\(\) -fnesc-gcc=gc                                                                                                                                                 c -Wall -Wshadow -Wnesc-all -target=micaz -fnesc-cfile=simbuild/micaz/app.c -boa                                                                                                                                                 rd=micasb -DDEFINED_TOS_AM_GROUP=0x22 --param max-inline-insns-single=100000 -DI                                                                                                                                                 DENT_APPNAME=\"BlinkAppC\" -DIDENT_USERNAME=\"kosheila\" -DIDENT_HOSTNAME=\"FIT-                                                                                                                                                 PC\" -DIDENT_USERHASH=0xa711198cL -DIDENT_TIMESTAMP=0x5666b42fL -DIDENT_UIDHASH=                                                                                                                                                 0x10c7ea07L -Wno-nesc-data-race BlinkAppC.nc   -fnesc-dump=components -fnesc-dum                                                                                                                                                 p=variables -fnesc-dump=constants -fnesc-dump=typedefs -fnesc-dump=interfacedefs                                                                                                                                                  -fnesc-dump=tags -fnesc-dumpfile=app.xml
Unknown target micaz
Known targets for TinyOS directory /opt/tinyos-2.x/tos
and the specified include directories are:
  epic eyesIFXv1 eyesIFXv2 intelmote2 iris mica2 mica2dot micaz mulle null shimm                                                                                                                                                 er shimmer2 telosa telosb tinynode
/opt/tinyos-2.x/support/make/sim.extra:66: recipe for target 'sim-exe' failed
make: *** [sim-exe] Error 2

**Comment by mahdi123456789** [comment]
how i can fix this problem help me please ,
mahdi@mahdi-Aspire-E1-530:/opt/tinyos-2.1.2/apps/Blink$ make telosb
mkdir -p build/telosb
mkdir: cannot create directory ‘build’: Permission denied
/opt/tinyos-2.1.2/support/make/msp/msp.rules:120: recipe for target 'builddir' failed
make: *** [builddir] Error 1
