### ISSUE TITLE
tinyos-release: Packages 'nesc', 'tinyos-tools' and 'msp430-46' throw errors; 'avr-tinyos' is not all installable 

### ISSUE THREAD

**Issue by fossterer** [tinyos/tinyos-main#308]
None of the packages listed at the download page 'http://tinyprod.net/repos/debian/' are installable

Outputs:
- sudo apt-get install nesc
...
Error: Package X is trying to overwrite the file Y. File Y is already provided by package Z
...
- sudo apt-get install tinyos-tools
...
Unpacking tinyos-tools (1.4.2-tinyprod1) ...
dpkg: error processing archive tinyos-tools_1.4.2-tinyprod1_i386.deb (--install):
 trying to overwrite '/usr/bin/uisp', which is also in package uisp 20050207-4.2ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
...
- sudo apt-get install msp430-46
...
Error: Package X is trying to overwrite the file Y. File Y is already provided by package Z
...
- sudo apt-get install avr-tinyos
...
dpkg: dependency problems prevent configuration of avr-tinyos:
 avr-tinyos depends on avr-tinyos-base; however:
  Package avr-tinyos-base is not installed.
 avr-tinyos depends on avr-binutils-tinyos; however:
  Package avr-binutils-tinyos is not installed.
 avr-tinyos depends on avr-gcc-tinyos; however:
  Package avr-gcc-tinyos is not installed.
 avr-tinyos depends on avr-libc-tinyos; however:
  Package avr-libc-tinyos is not installed.
 avr-tinyos depends on avrdude-tinyos; however:
  Package avrdude-tinyos is not installed.
...

**Comment by tundo91** [comment]
@danielemidi i have same the problem. Ubuntu 13.10.
I solved following this:
http://www.cse.wustl.edu/~lu/cse467s/slides/tinyos-installation.pdf
Basically using **squeeze** repository instead of **wheezy**

**Comment by Nikolopoulos** [comment]
@tundo91 Holy $hit man, you save my life, THANKS A LOT!
