### ISSUE TITLE
Conflict ssize_t between tinyos coap library and nxp toolchain

### ISSUE THREAD

**Issue by tim-bormann** [tinyos/tinyos-main#321]
We are porting tinyos to the jn5168 platform, and have a problem
The coap c lib defines ssize_t (as an unsigned integer, which is wrong anyhow), but the jennic toolchain defines this type as well, but hidden in binaries.

How to resolve that iusse ?

**Comment by cire831** [comment]
so what was the resolution?

**Comment by tim-bormann** [comment]
no resolution yet, but we figured this the wrong place to ask. this concerns libcoap, which is independent from tinyos.
