### ISSUE TITLE
[ERROR] Your version of tinyos-tools is too old (<2.2.0)

### ISSUE THREAD

**Issue by ckalas** [tinyos/tinyos-main#330]
I just managed to install following your guidelines with some modifications to get it to work with brew on OSX Yosemite, but now I get this error making Blink:

make telosb
/bin/bash: tos-ident-flags: command not found
../../support/make/Makerules:162: *** [ERROR] Your version of tinyos-tools is too old (<2.2.0).Please build and install the tinyos-tools in the tinyos-main/tools directory.  Stop.

Is this error because it couldn't find tos-ident-flags, or because for some reason there seems to be a genuine version mixup?

**Comment by cire831** [comment]
what tinyos source did you use?
