### ISSUE TITLE
What is the relationship between tinyOS and TinyDB？

### ISSUE THREAD

**Issue by KnightThor** [tinyos/tinyos-main#339]
This few days,I do some research with TinyDB.Why i can't find any informations about TinyDB in TinyOS 2.1.2.1?

**Comment by cire831** [comment]
you should ask this kind of question on the tinyos-help mailing list.

If memory serves, TinyDB was a TinyOS 1 thing.  It didn't make it over to TinyOS 2.  Most likely because no one took the time to port it.

**Comment by KnightThor** [comment]
Thank you very much.You helped me a lot.

2015-04-22 15:06 GMT+08:00 Eric Decker <notifications@github.com>:
