### ISSUE TITLE
Tinyos 1.x download

### ISSUE THREAD

**Issue by xianlin** [tinyos/tinyos-main#344]
Can I use 2.x to compile 1.x code? I think it's not compatible.

How to download/git clone TinyOS1.X? I have some old sensors need to use the old code. Thanks.

**Comment by xianlin** [comment]
never mind and I have found the link:

How To Install TinyOS 1.x
http://leme.tagus.ist.utl.pt/gems/PmWiki/index.php/resources/HowToInstallTinyOS

**Comment by cire831** [comment]
TinyOS 2.x is a different code base from TinyOS 1.x.  They are not compatible.  One doesn't use 2.x to compile anything.  Rather one combines ones code with modules from TinyOS 2.x then compile the result using an appropriate toolchain for ones h/w.

Sorry, I don't remember where one can get TinyOS 1 code.
