### ISSUE TITLE
Stuck with errors while creating a new module with interface

### ISSUE THREAD

**Issue by jdcpower1994** [tinyos/tinyos-main#346]
here is my code
(module) PowerupC.nc http://pastebin.com/VWX7dEpw
(config) PwoerupAppC.nc http://pastebin.com/G5TrZXTA
(my own module) jigsM.nc http://pastebin.com/dTug4n68
(my own interface) jigs.nc http://pastebin.com/G554FaTh
(Makefile) Makefile http://pastebin.com/6AMrezSp

when I do make micaz sim
it gives error like .:
In component `jigsM':
jigsM.nc:10: `jigs.led1On' not implemented
make: *** [sim-exe] Error 1

**Comment by cire831** [comment]
please don't use github issues for asking for help.

it is for submitting bugs against the code base itself.
