### ISSUE TITLE
Ppprouter application error

### ISSUE THREAD

**Issue by kentstudent** [tinyos/tinyos-main#349]
Hi, 

I'm trying to build the ppprouter application using the "make telosb blip" command and getting the following error at the end of the output: 
collect2: ld returned 1 exit status
make: **\* [exe] Error 1

I have searched on Github and other forums for this error but can't seem to find a solution. Any help greatly appreciated. Thanks in advance. 

edit: using the latest checkout of TinyOS from github and used the http://tinyprod.net/debian-dev/ repository. The error is the same as described in this link: http://tinyos-help.10906.n7.nabble.com/error-make-exe0-Error-1-in-Blip2-td22486.html

**Comment by cire831** [comment]
can you please run this build again but with "verbose" in the make command.

then submit the entire output.

are you building off the current tip of the tinyos-main trunk?


On Tue, Sep 1, 2015 at 5:04 PM, kentstudent <notifications@github.com>
wrote:

> Hi,
>
> I'm trying to build the ppprouter application using the "make telosb"
> command and getting the following error at the end of the output:
> collect2: ld returned 1 exit status
> make: *** [exe] Error 1
>
> I have searched on Github and other forums for this error but can't seem
> to find a solution. Any help greatly appreciated. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinyos/tinyos-main/issues/349>.
>



-- 
Eric B. Decker
Senior (over 50 :-) Researcher

**Comment by kentstudent** [comment]
Hi,  
Thanks for the reply. Yes it is from https://github.com/tinyos/tinyos-main.git
Heres the output: 

GNU C (GCC) version 4.6.3 20120301 (mspgcc LTS 20120406 unpatched) (msp430)
	compiled by GNU C version 4.4.5, GMP version 4.3.2, MPFR version 3.0.0, MPC version 0.9
GGC heuristics: --param ggc-min-expand=98 --param ggc-min-heapsize=128460
ignoring nonexistent directory "/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/sys-include"
ignoring duplicate directory "/usr/bin/../lib/gcc/../../lib/gcc/msp430/4.6.3/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/../../lib/gcc/msp430/4.6.3/include-fixed"
ignoring nonexistent directory "/usr/bin/../lib/gcc/../../lib/gcc/msp430/4.6.3/../../../../msp430/sys-include"
ignoring duplicate directory "/usr/bin/../lib/gcc/../../lib/gcc/msp430/4.6.3/../../../../msp430/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/ncc
 ../../tos/lib/ppp
 ../../tos/lib/fragpool
 ../../tos/lib/net/
 ../../tos/lib/printf/
 ../../tools/tinyos/c/blip/
 ../../tos/lib/net/blip/
 ../../tos/lib/net/blip/interfaces/
 ../../tos/lib/net/blip/nwprog/
 ../../tos/lib/net/blip/shell/
 ../../tos/lib/net/blip/serial/
 ../../tos/lib/net/blip/platform/
 ../../tos/lib/net/blip/icmp/
 ../../tos/lib/net/blip/dhcp/
 ../../tos/lib/net/rpl
 ../../tos/platforms/telosb
 ../../tos/platforms/telosb/chips/stm25p
 ../../tos/platforms/telosa
 ../../tos/platforms/telosa/chips/cc2420
 ../../tos/platforms/telosa/chips/s1087
 ../../tos/platforms/telosa/chips/s10871
 ../../tos/platforms/telosa/chips/sht11
 ../../tos/platforms/epic/chips/ds2411
 ../../tos/chips/cc2420
 ../../tos/chips/cc2420/alarm
 ../../tos/chips/cc2420/control
 ../../tos/chips/cc2420/csma
 ../../tos/chips/cc2420/interfaces
 ../../tos/chips/cc2420/link
 ../../tos/chips/cc2420/lowpan
 ../../tos/chips/cc2420/lpl
 ../../tos/chips/cc2420/packet
 ../../tos/chips/cc2420/receive
 ../../tos/chips/cc2420/spi
 ../../tos/chips/cc2420/transmit
 ../../tos/chips/cc2420/unique
 ../../tos/chips/cc2420/security
 ../../tos/chips/msp430
 ../../tos/chips/msp430/adc12
 ../../tos/chips/msp430/dma
 ../../tos/chips/msp430/pins
 ../../tos/chips/msp430/timer
 ../../tos/chips/msp430/usart
 ../../tos/chips/msp430/sensors
 ../../tos/chips/stm25p
 ../../tos/chips/sht11
 ../../tos/chips/ds2411
 ../../tos/lib/timer
 ../../tos/lib/serial
 ../../tos/lib/power
 ../../tos/lib/onewire
 ../../tos/system
 ../../tos/types
 ../../tos/interfaces
 /usr/bin/../lib/gcc/msp430/4.6.3/include
 /usr/bin/../lib/gcc/msp430/4.6.3/include-fixed
 /usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/include
End of search list.
GNU C (GCC) version 4.6.3 20120301 (mspgcc LTS 20120406 unpatched) (msp430)
	compiled by GNU C version 4.4.5, GMP version 4.3.2, MPFR version 3.0.0, MPC version 0.9
GGC heuristics: --param ggc-min-expand=98 --param ggc-min-heapsize=128460
Compiler executable checksum: 7f4e21113cbe3069af1f3270edd03326
COLLECT_GCC_OPTIONS='-I' '/usr/lib/ncc' '-o' 'build/telosb/main.exe' '-Os' '-I' '../../tos/lib/ppp' '-I' '../../tos/lib/fragpool' '-D' 'IN6_PREFIX="fec0::"' '-D' 'BLIP_ADDR_AUTOCONF=0' '-D' 'RPL_ADDR_AUTOCONF=0' '-D' 'BLIP_SEND_ROUTER_SOLICITATIONS=0' '-D' 'BLIP_SEND_ROUTER_ADVERTISEMENTS=1' '-D' 'LIB6LOWPAN_HC_VERSION=6' '-D' 'RPL_ROUTING=1' '-D' 'RPL_STORING_MODE=1' '-D' 'RPL_OF_0=1' '-D' 'RPL_OF_MRHOF=0' '-D' 'PPP_HDLC_RX_FRAME_LIMIT=1' '-D' 'PPP_HDLC_TX_FRAME_LIMIT=8' '-D' 'NEW_PRINTF_SEMANTICS' '-D' 'PRINTFUART_ENABLED' '-D' 'CC2420_HW_ACKNOWLEDGEMENTS' '-D' 'CC2420_HW_ADDRESS_RECOGNITION' '-D' 'RFA1_HARDWARE_ACK' '-D' 'RFA1_HWACK_64BIT' '-D' 'RF230_HARDWARE_ACK' '-D' 'RF230_HWACK_64BIT' '-D' 'IEEE154BARE_ENABLED' '-D' 'PACKET_LINK' '-D' 'TOSH_DATA_LENGTH=112' '-I' '../../tos/lib/net/' '-I' '../../tos/lib/printf/' '-I' '../../tools/tinyos/c/blip/' '-I' '../../tos/lib/net/blip/' '-I' '../../tos/lib/net/blip/interfaces/' '-I' '../../tos/lib/net/blip/nwprog/' '-I' '../../tos/lib/net/blip/shell/' '-I' '../../tos/lib/net/blip/serial/' '-I' '../../tos/lib/net/blip/platform/' '-I' '../../tos/lib/net/blip/icmp/' '-I' '../../tos/lib/net/blip/dhcp/' '-I' '../../tos/lib/net/rpl' '-v' '-I' '../../tos/platforms/telosb' '-I' '../../tos/platforms/telosb/chips/stm25p' '-I' '../../tos/platforms/telosa' '-I' '../../tos/platforms/telosa/chips/cc2420' '-I' '../../tos/platforms/telosa/chips/s1087' '-I' '../../tos/platforms/telosa/chips/s10871' '-I' '../../tos/platforms/telosa/chips/sht11' '-I' '../../tos/platforms/epic/chips/ds2411' '-I' '../../tos/chips/cc2420' '-I' '../../tos/chips/cc2420/alarm' '-I' '../../tos/chips/cc2420/control' '-I' '../../tos/chips/cc2420/csma' '-I' '../../tos/chips/cc2420/interfaces' '-I' '../../tos/chips/cc2420/link' '-I' '../../tos/chips/cc2420/lowpan' '-I' '../../tos/chips/cc2420/lpl' '-I' '../../tos/chips/cc2420/packet' '-I' '../../tos/chips/cc2420/receive' '-I' '../../tos/chips/cc2420/spi' '-I' '../../tos/chips/cc2420/transmit' '-I' '../../tos/chips/cc2420/unique' '-I' '../../tos/chips/cc2420/security' '-I' '../../tos/chips/msp430' '-I' '../../tos/chips/msp430/adc12' '-I' '../../tos/chips/msp430/dma' '-I' '../../tos/chips/msp430/pins' '-I' '../../tos/chips/msp430/timer' '-I' '../../tos/chips/msp430/usart' '-I' '../../tos/chips/msp430/sensors' '-I' '../../tos/chips/stm25p' '-I' '../../tos/chips/sht11' '-I' '../../tos/chips/ds2411' '-I' '../../tos/lib/timer' '-I' '../../tos/lib/serial' '-I' '../../tos/lib/power' '-I' '../../tos/lib/onewire' '-mmcu=msp430f1611' '-D' 'PLATFORM_TELOSB' '-Wall' '-Wshadow' '-I' '../../tos/system' '-I' '../../tos/types' '-I' '../../tos/interfaces' '-D' 'IDENT_APPNAME="PppRouterC"' '-D' 'IDENT_USERNAME="root"' '-D' 'IDENT_HOSTNAME="tinyos"' '-D' 'IDENT_USERHASH=0x69f6412fL' '-D' 'IDENT_TIMESTAMP=0x55e975dbL' '-D' 'IDENT_UIDHASH=0xc8e594c3L' '-D' 'NESC=136' '-mcpu=430' '-mmpy=16' '-mivcnt=16'
 /usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/as -mcpu=430 -mmcu=msp430f1611 -o /tmp/ccpJBMRV.o /tmp/cc1kDjFz.s
COMPILER_PATH=/usr/bin/../libexec/gcc/msp430/4.6.3/:/usr/bin/../libexec/gcc/:/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/
LIBRARY_PATH=/usr/bin/../lib/gcc/msp430/4.6.3/mmpy-16/:/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/lib/mmpy-16/:/usr/bin/../lib/gcc/msp430/4.6.3/:/usr/bin/../lib/gcc/:/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/lib/
COLLECT_GCC_OPTIONS='-I' '/usr/lib/ncc' '-o' 'build/telosb/main.exe' '-Os' '-I' '../../tos/lib/ppp' '-I' '../../tos/lib/fragpool' '-D' 'IN6_PREFIX="fec0::"' '-D' 'BLIP_ADDR_AUTOCONF=0' '-D' 'RPL_ADDR_AUTOCONF=0' '-D' 'BLIP_SEND_ROUTER_SOLICITATIONS=0' '-D' 'BLIP_SEND_ROUTER_ADVERTISEMENTS=1' '-D' 'LIB6LOWPAN_HC_VERSION=6' '-D' 'RPL_ROUTING=1' '-D' 'RPL_STORING_MODE=1' '-D' 'RPL_OF_0=1' '-D' 'RPL_OF_MRHOF=0' '-D' 'PPP_HDLC_RX_FRAME_LIMIT=1' '-D' 'PPP_HDLC_TX_FRAME_LIMIT=8' '-D' 'NEW_PRINTF_SEMANTICS' '-D' 'PRINTFUART_ENABLED' '-D' 'CC2420_HW_ACKNOWLEDGEMENTS' '-D' 'CC2420_HW_ADDRESS_RECOGNITION' '-D' 'RFA1_HARDWARE_ACK' '-D' 'RFA1_HWACK_64BIT' '-D' 'RF230_HARDWARE_ACK' '-D' 'RF230_HWACK_64BIT' '-D' 'IEEE154BARE_ENABLED' '-D' 'PACKET_LINK' '-D' 'TOSH_DATA_LENGTH=112' '-I' '../../tos/lib/net/' '-I' '../../tos/lib/printf/' '-I' '../../tools/tinyos/c/blip/' '-I' '../../tos/lib/net/blip/' '-I' '../../tos/lib/net/blip/interfaces/' '-I' '../../tos/lib/net/blip/nwprog/' '-I' '../../tos/lib/net/blip/shell/' '-I' '../../tos/lib/net/blip/serial/' '-I' '../../tos/lib/net/blip/platform/' '-I' '../../tos/lib/net/blip/icmp/' '-I' '../../tos/lib/net/blip/dhcp/' '-I' '../../tos/lib/net/rpl' '-v' '-I' '../../tos/platforms/telosb' '-I' '../../tos/platforms/telosb/chips/stm25p' '-I' '../../tos/platforms/telosa' '-I' '../../tos/platforms/telosa/chips/cc2420' '-I' '../../tos/platforms/telosa/chips/s1087' '-I' '../../tos/platforms/telosa/chips/s10871' '-I' '../../tos/platforms/telosa/chips/sht11' '-I' '../../tos/platforms/epic/chips/ds2411' '-I' '../../tos/chips/cc2420' '-I' '../../tos/chips/cc2420/alarm' '-I' '../../tos/chips/cc2420/control' '-I' '../../tos/chips/cc2420/csma' '-I' '../../tos/chips/cc2420/interfaces' '-I' '../../tos/chips/cc2420/link' '-I' '../../tos/chips/cc2420/lowpan' '-I' '../../tos/chips/cc2420/lpl' '-I' '../../tos/chips/cc2420/packet' '-I' '../../tos/chips/cc2420/receive' '-I' '../../tos/chips/cc2420/spi' '-I' '../../tos/chips/cc2420/transmit' '-I' '../../tos/chips/cc2420/unique' '-I' '../../tos/chips/cc2420/security' '-I' '../../tos/chips/msp430' '-I' '../../tos/chips/msp430/adc12' '-I' '../../tos/chips/msp430/dma' '-I' '../../tos/chips/msp430/pins' '-I' '../../tos/chips/msp430/timer' '-I' '../../tos/chips/msp430/usart' '-I' '../../tos/chips/msp430/sensors' '-I' '../../tos/chips/stm25p' '-I' '../../tos/chips/sht11' '-I' '../../tos/chips/ds2411' '-I' '../../tos/lib/timer' '-I' '../../tos/lib/serial' '-I' '../../tos/lib/power' '-I' '../../tos/lib/onewire' '-mmcu=msp430f1611' '-D' 'PLATFORM_TELOSB' '-Wall' '-Wshadow' '-I' '../../tos/system' '-I' '../../tos/types' '-I' '../../tos/interfaces' '-D' 'IDENT_APPNAME="PppRouterC"' '-D' 'IDENT_USERNAME="root"' '-D' 'IDENT_HOSTNAME="tinyos"' '-D' 'IDENT_USERHASH=0x69f6412fL' '-D' 'IDENT_TIMESTAMP=0x55e975dbL' '-D' 'IDENT_UIDHASH=0xc8e594c3L' '-D' 'NESC=136' '-mcpu=430' '-mmpy=16' '-mivcnt=16'
 /usr/bin/../libexec/gcc/msp430/4.6.3/collect2 -m msp430 -o build/telosb/main.exe /usr/bin/../lib/gcc/msp430/4.6.3/mmpy-16/crt0ivtbl16.o -L/usr/bin/../lib/gcc/msp430/4.6.3/mmpy-16 -L/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/lib/mmpy-16 -L/usr/bin/../lib/gcc/msp430/4.6.3 -L/usr/bin/../lib/gcc -L/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/lib /tmp/ccZH8auj.o -lm /tmp/ccJVAW0P.o /tmp/cc14aMB6.o /tmp/ccAVIwpn.o /tmp/ccHIowyE.o /tmp/ccpJBMRV.o -lgcc -lc -lgcc -lcrt0 -L /usr/bin/../lib/gcc/../../msp430/lib/ldscripts/msp430f1611/
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: build/telosb/main.exe section `.text' will not fit in region `rom'
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .text loaded at [00004000,0001096f]
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `rom' overflowed by 5012 bytes
/usr/bin/../lib/gcc/msp430/4.6.3/mmpy-16/libcrt0.a(_copy_data.o): In function `__do_copy_data':
/home/cire/mm/tinyos-main/tinyos-2.x/packaging/msp430-46/gcc-4.6.3/build/gcc/../../gcc/config/msp430/crt0.S:195: relocation truncated to fit: R_MSP430_16_BYTE against symbol `__data_load_start' defined in *ABS* section in build/telosb/main.exe
/tmp/ccZH8auj.o: In function `LcpAutomatonP__1__calculateEventActions_':
app.c:(.text+0x542): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/tmp/ccZH8auj.o: In function `LcpAutomatonP__0__calculateEventActions_':
app.c:(.text+0x8ec): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/tmp/ccZH8auj.o: In function `printf_in6addr':
app.c:(.text+0xca0): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/tmp/ccZH8auj.o: In function `RPLRankP__insertParent':
app.c:(.text+0xe30): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/tmp/ccZH8auj.o: In function `printf_ieee154addr':
app.c:(.text+0x1362): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
app.c:(.text+0x136e): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
app.c:(.text+0x1386): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
app.c:(.text+0x1398): undefined reference to `putchar'
/tmp/ccZH8auj.o: In function `IPDispatchP__lowpan_recon_start':
app.c:(.text+0x1e70): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/tmp/ccZH8auj.o: In function `IPDispatchP__reconstruct_age':
app.c:(.text+0x22a0): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
app.c:(.text+0x22d4): additional relocation overflows omitted from the output
/tmp/ccZH8auj.o: In function `IPNeighborDiscoveryP__IPForward__send':
app.c:(.text+0x2c32): undefined reference to `putchar'
/tmp/ccZH8auj.o: In function `IPProtocolsP__IP__send.isra.278':
app.c:(.text+0x4268): undefined reference to `putchar'
app.c:(.text+0x4316): undefined reference to `putchar'
/tmp/ccZH8auj.o: In function `IPForwardingEngineP__IPForward__recv.isra.327':
app.c:(.text+0x53ac): undefined reference to `putchar'
/tmp/ccZH8auj.o:app.c:(.text+0x62dc): more undefined references to `putchar' follow
collect2: ld returned 1 exit status
make: *** [exe] Error 1
root@tinyos:~/tinyos-main/apps/PppRouter#

**Comment by vlahan** [comment]
PppRouter currently does not fit on the TelosB. As the error message says:

/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: build/telosb/main.exe section .text' will not fit in regionrom'
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .text loaded at [00004000,0001096f]
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region rom' overflowed by 5012 bytes

Take a look at the thread:

http://mail.millennium.berkeley.edu/pipermail/tinyos-help/2014-August/058544.html

There are several ways one can try to hack down the size, by removing different components of BLIP.

**Comment by cire831** [comment]
it hasn't fit for awhile.  telosb is using the msp430f1611 which has if
memory serves 48KB of ROM.

I've been using the msp430f5438a which has more but still has problems
because of the tool chain.  Getting code into the upper > 64K rom space is
problematic.

On Sat, Sep 5, 2015 at 8:58 AM, Vlado Handziski <notifications@github.com>
wrote:

> PppRouter currently does not fit on the TelosB. As the error message says:
>
> /usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld:
> build/telosb/main.exe section .text' will not fit in regionrom'
> /usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section
> .vectors loaded at [0000ffe0,0000ffff] overlaps section .text loaded at
> [00004000,0001096f]
> /usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region rom'
> overflowed by 5012 bytes
>
> Take a look at the thread:
>
>
> http://mail.millennium.berkeley.edu/pipermail/tinyos-help/2014-August/058544.html
>
> There are several ways one can try to hack down the size, by removing
> different components of BLIP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinyos/tinyos-main/issues/349#issuecomment-137970654>.
>



-- 
Eric B. Decker
Senior (over 50 :-) Researcher

**Comment by kentstudent** [comment]
I initially tried to disable just the "components UDPShellC;" but still overflowed as below: 

/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: build/telosb/main.exe section `.text' will not fit in region `rom'
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .text loaded at [00004000,0001018f]
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `rom' overflowed by 2512 bytes

In the end disabled the following in the ppprouter.nc file as suggested in the link provided by @vlahan and the compile was successful. 
components RouteCmdC;
components UDPShellC;

[INFO] script
           45678 bytes in ROM
            9270 bytes in RAM
[INFO] size (toolchain):
   text	   data	    bss	    dec	    hex	filename
  45878	    132	   9140	  55150	   d76e	build/telosb/main.exe
[INFO] generating symbol table
[INFO] generating listing
[INFO] creating ihex file
[INFO] writing TOS image
[INFO] writing TOS buildinfo
[INFO] running the wiring check

For the time being this is ok for me. Thank you both for your help.

**Comment by navneetnivu07** [comment]
Hi, everyone! Even I'm getting the same error. What is the solution? Or is there any workaround?

**Comment by cire831** [comment]
sorry the solution is to either wack what is being included or move to a more modern larger mote.

ppprouter hasn't fit for quite some time.

got back and read all the notes on this issue and you'll see what is going on.

**Comment by navneetnivu07** [comment]
Thank you sir 👍  @cire831
