### ISSUE TITLE
region `ram' overflowed error when making for telosb

### ISSUE THREAD

**Issue by saeedek** [tinyos/tinyos-main#364]
Hello,
I have written a simple app to read from a fake acc sensor with fake data and when I try to make it for the Telosb I get this error 

user@instant-contiki:~/tinyos-main/apps/Saeed$ make telosb
mkdir -p build/telosb
    compiling PNMoteAppC to a telosb binary
ncc -o build/telosb/main.exe  -Os -fnesc-separator=__ -Wall -Wshadow -Wnesc-all -target=telosb -fnesc-cfile=build/telosb/app.c -board= -DDEFINED_TOS_AM_GROUP=0x22 -DIDENT_APPNAME=\"PNMoteAppC\" -DIDENT_USERNAME=\"user\" -DIDENT_HOSTNAME=\"instant-contiki\" -DIDENT_USERHASH=0x22a1ff22L -DIDENT_TIMESTAMP=0x56a0b835L -DIDENT_UIDHASH=0x86af45e6L  PNMoteAppC.nc -lm 
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: build/telosb/main.exe section `.data' will not fit in region `ram'
/usr/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `ram' overflowed by 9030 bytes
collect2: ld returned 1 exit status
make: *** [exe0] Error 1

-----------------------------------------
and this is my app:

#include "Timer.h"

module PNMoteApp {

	uses {

	interface Boot;

	interface Timer<TMilli> as MilliTimer;

	interface Read<uint16_t> as ACCSensor;

	interface SplitControl as ACCControl;

  }

  

} implementation {

	

	//***************** Boot interface ********************//

	event void Boot.booted() {

		dbg("boot","Application booted.\n");

		call ACCControl.start();

  	}

  	event void ACCControl.startDone(error_t err){

		int i=0;

		dbg("boot","Start Done.\n");

		for(i=0;i<4;i++){

			call ACCSensor.read();

		}	

 	}

  	event void ACCControl.stopDone(error_t err){

  	};

  

  	//***************** MilliTimer interface ********************//

  	event void MilliTimer.fired() {

		dbg("boot","Read Timer Fired.\n");

 		call ACCSensor.read();	

  	}	

  

 	 //************************* Read interface **********************//

  	event void ACCSensor.readDone(error_t result, uint16_t data) {

		dbg("boot","acc read done %d\n",data);

  	}	
}

**Comment by cire831** [comment]
not enough information to determine what is causing this problem.

But something is filling RAM in your code.

please take this over to the tinyos-help mailing list.  rather than filling an issue.
