### ISSUE TITLE
msp430-gcc: l/opt/tinyos-2.1.2/tos/lib/printf: No such file or directory make: *** [exe0] Error 1

### ISSUE THREAD

**Issue by tony00707** [tinyos/tinyos-main#384]
After compiling my program i got this erorr msp430-gcc: l/opt/tinyos-2.1.2/tos/lib/printf: No such file or directory make: *** [exe0] Error 1. Can anyone here help me? Please

Module file
#include<Timer.h>
#include<stdio.h>
#include<string.h>

module TempTestC
{
	uses
	{
		//General interface
		interface Boot;
		interface Timer<TMilli>;
		interface Leds;
		
		//Read
		interface Read<uint16_t> as TempRead;
		}
}
implementation
{

	event void Boot.booted()
	{
		call Timer.startPeriodic(1000);
		call Leds.led1On();
	}

	event void Timer.fired()
	{
		if(call TempRead.read() == SUCCESS)
		{
			call Leds.led2Toggle();
		}
		else
		{
			call Leds.led0Toggle();
			}
		}
		
	
		event void TempRead.readDone(error_t result, uint16_t val)
		{
			if(result == SUCCESS)
			{
				printf("Current Temp is: %d",val);
				}
				else
				{
					printf("Error reading from sensor!");
				
					}
					}
}

Configuration file

configuration TempTestAppC
{
}
implementation
{
	//General components
	components TempTestC as App;
	components MainC, LedsC;
	components new TimerMilliC();
	
	
   App.Boot -> MainC;
   App.Leds -> LedsC;
   App.Timer -> TimerMilliC;
   
   
   //Temperature component
   components new SensirionSht11C() as TempSensor;
   
   App.TempRead -> TempSensor.Temperature;
   
}

Makefile

COMPONENT = TempTestAppC
CFLAGS+=l$(TOSDIR)/lib/printf
include $(MAKERULES)

Thanks.

**Comment by cire831** [comment]
hi tony,

this is not the place for this question....

you should post this on the mailing list tinyos-help (tinyos-help@millennium.berkeley.edu)

email me directly and I'll see if we can figure it out.
