### ISSUE TITLE
cant execute make for new platform

### ISSUE THREAD

**Issue by shyandsy** [tinyos/tinyos-main#392]
# updated on 206-12-19 2:21
try to figure out the problem followed this instruction: https://github.com/tinyos/tinyos-main/tree/master/support/make

it leads to new problems which said warning Unable to identify and include MCU header, use -mmcu=MCU, and also a lots of undeclared error

![image](https://cloud.githubusercontent.com/assets/5271457/21305586/2ea01072-c592-11e6-9d4a-17d2aa0aa0f4.png)
![image](https://cloud.githubusercontent.com/assets/5271457/21305596/3c1c3654-c592-11e6-8e50-dd96cf11f2de.png)

```
In file included from ../../tos/chips/msp430/msp430hardware.h:42,
                 from ../../tos/platforms/telosb/hardware.h:4,
                 from ../../tos/system/SchedulerBasicP.nc:52:
/usr/local/msp430/lib/gcc/msp430/4.6.3/../../../../msp430/include/msp430.h:930:2: warning: #warning Unable to identify and include MCU header, use -mmcu=MCU

```

# guess
in the section "Converting the .platform File." of the document
![image](https://cloud.githubusercontent.com/assets/5271457/21305619/5ddc70ba-c592-11e6-9750-25a0efa9002d.png)

could you give some detail information where should I and how to write this part of code?
![image](https://cloud.githubusercontent.com/assets/5271457/21305655/8ba42f2e-c592-11e6-8b46-d4084799da4f.png)

------------------------------------------------------------------------------------------------

# Original Question
add genomote platform to new version of TinyOS.

# what i have done
from old version to new version
1. copy tos/platforms/genomote/    => tos/platforms/genomote/
2. copy support/make/genomote/    => support/make/genomote/
3. copy support/make/genomote.target   =>  support/make/target/genomote.target
4. created a empty file support/make/platforms/genomote.platform
5. installed the mas430-gcc, and the make telosb works fine

the content of genomote.target is
```
#-*-Makefile-*- vim:syntax=make
#$Id$

TARGET = genomote

#MSP_MCU = msp430x1611

# Disable MSP430 hardware multiply because it makes MSPGCC die
PFLAGS += -mdisable-hwmul
OPTFLAGS += -O

MSP_BSL ?= tos-bsl
MSP_BSL_FLAGS = --telosb

VOLUME_FILE = volumes-stm25p.xml
VOLUME_ALLOCATOR = tos-storage-stm25p

ifdef CC2420_CHANNEL
PFLAGS += -DCC2420_DEF_CHANNEL=$(CC2420_CHANNEL)
endif

# So that I know when I am compiling for genomote
CFLAGS += -DGENOMOTE

$(call TOSMake_include_platform,genomote)

ifeq ($(filter master slave,$(MAKECMDGOALS)),)
%:
	@echo "ERROR: Please specify whether you are compiling for master or slave"
else
genomote: $(BUILD_DEPS)
	@:
endif
```

the content of genomote.platform is
```
#-*-Makefile-*- vim:syntax=make
```

# error
when I execute the command    make genomote master
i got the following error message
```
nescc -o build/genomote/main.exe   -Os -O -gcc= -Wnesc-all -fnesc-include=tos -fnesc-scheduler=TinySchedulerC,TinySchedulerC.TaskBasic,TaskBasic,TaskBasic,runTask,postTask -fnesc-cfile=build/genomote/app.c -fnesc-separator=__ -mdisable-hwmul -DPLATFORM_GENOMOTE -I../../tos/system -I../../tos/types -I../../tos/interfaces -DIDENT_APPNAME=\"BlinkAppC\" -DIDENT_USERNAME=\"shyandsy\" -DIDENT_HOSTNAME=\"localhost.local\" -DIDENT_USERHASH=0x6c6cbabbL -DIDENT_TIMESTAMP=0x5856e078L -DIDENT_UIDHASH=0x32ed028cL -DGENOMOTE -fnesc-dump=wiring -fnesc-dump='interfaces(!abstract())' -fnesc-dump='referenced(interfacedefs, components)' -fnesc-dumpfile=build/genomote/wiring-check.xml BlinkAppC.nc   
Couldn't execute 
make: *** [exe] Error 2
```
![image](https://cloud.githubusercontent.com/assets/5271457/21295882/2da86dc2-c524-11e6-913f-63fb4131b23f.png)

# comments
I saw there is a README document under support/make/platform, and it said the new version TinyOS separate platforms from targets, but I dont know how to do it. The target file shows above.

**Comment by cire831** [comment]
this is not the place for this.

please take this over to tinyos-help@millennium.berkeley.edu

**Comment by shyandsy** [comment]
@cire831  
according to my expriment, there is a mistake on the document for upgrade platform from 2 to 3

if you wanna fix that, i will show u

**Comment by cire831** [comment]
yes please, email directly, cire831@gmail.com
