### ISSUE TITLE
msp430.usart.msp430uartp don't implement interface completely

### ISSUE THREAD

**Issue by drchen00** [tinyos/tinyos-main#397]
msp430uartP.nc don't implemnet the interface of UartByte. Commands of sendAvail and receiveAvail are missing.

**Comment by cire831** [comment]
next time please provide a better bug report.  typically one would include the information about what tree you are working on and what program you are compiling.

In other words, make it easy for the developers working in their spare time to find and fix the problem.  That will increase the likelihood of the problem getting worked on.

That said, I'll fix it.  I know what's wrong (I did it).

**Comment by cire831** [comment]
fixed by 72df108
