### ISSUE TITLE
.img file for tinyOS

### ISSUE THREAD

**Issue by rupipal** [tinyos/tinyos-main#413]
Hi,
Could somebody share a .img file for tinyOS that I can use to bootup with Qemu on Debian Linux?
Actually, I'm working inside fakeroot GNURoot Debian apk on Android. I've could boot Linux inside that container with Qemu. Just it didn't interface ok with virtual keyboard of android phone.

regards
Rupinder

**Comment by cire831** [comment]
try posting on tinyos-help@millennium.berkeley.edu

this isn't the place for this kind of request.

thanks.
