### ISSUE TITLE
Details About Pull Requests #414

### ISSUE THREAD

**Issue by inouetoukyou** [tinyos/tinyos-main#415]
I am happy that #414 was merged. Despite it merged or not, I wonder whether the file was upgraded or downgraded, because the original one in https://github.com/tinyos/tinyos-release/blob/tinyos-2_1_2/tools/tinyos/misc/tos-install-jni.in considers three platforms: Linux, Windows and Darwin, but this one only considers Windows.

**Comment by cire831** [comment]
looks like the process of installing jni on post 2.1.2 is different.  I suspect there is no longer anything needed from within the tinyos tree.

it looks like JNI gets installed from a native distribution repo.
