### ISSUE TITLE
I can't compile Blip Applications for Iris Motes

### ISSUE THREAD

**Issue by ngpjunior** [tinyos/tinyos-main#431]
I need to make a sensor network that use the Coap application protocol. For this I intend to use the standard applications of TinyOS Blip 2.0 PppRouter as base station and CoapBlip for the sensors. However, I'm having some problems compiling the applications. I have already tested compiling on different versions of Ubuntu and the same mistakes happen.

nelson@nelson-VirtualBox:~/tinyos-main/apps/PppRouter$ make iris blip
         [INFO] compiling PppRouterC to a iris binary
nescc -o build/iris/main.exe   -Os -I../../tos/lib/ppp -I../../tos/lib/fragpool -DRF230_DEF_CHANNEL=26 -DIN6_PREFIX=\"fec0::\" -DBLIP_ADDR_AUTOCONF=0 -DRPL_ADDR_AUTOCONF=0 -DBLIP_SEND_ROUTER_SOLICITATIONS=0 -DBLIP_SEND_ROUTER_ADVERTISEMENTS=1 -DBLIP_L2_RETRIES=5 -DBLIP_L2_DELAY=103 -DLIB6LOWPAN_HC_VERSION=6 -DRPL_ROUTING=1 -DRPL_STORING_MODE=1 -DRPL_OF_0=1 -DRPL_OF_MRHOF=0 -DLPL_SLEEP_INTERVAL=512 -DLPL_DEF_LOCAL_WAKEUP=512 -DLPL_DEF_REMOTE_WAKEUP=512 -DPPP_HDLC_RX_FRAME_LIMIT=1 -DPPP_HDLC_TX_FRAME_LIMIT=8 -DNEW_PRINTF_SEMANTICS -DPRINTFUART_ENABLED -gcc=avr-gcc -Wnesc-all -fnesc-include=tos -fnesc-scheduler=TinySchedulerC,TinySchedulerC.TaskBasic,TaskBasic,TaskBasic,runTask,postTask -fnesc-cfile=build/iris/app.c -fnesc-separator=__ -I../../tos/lib/net/rpl -DCC2420_HW_ACKNOWLEDGEMENTS -DCC2420_HW_ADDRESS_RECOGNITION -DRFA1_HARDWARE_ACK -DRFA1_HWACK_64BIT -DRF230_HARDWARE_ACK -DRF230_HWACK_64BIT -DIEEE154BARE_ENABLED -DPACKET_LINK
-DTOSH_DATA_LENGTH=112 -I../../tos/lib/net/ -I../../tos/lib/printf/ -I../../tools/tinyos/c/blip/ -I../../tos/lib/net/blip/ -I../../tos/lib/net/blip/interfaces/ -I../../tos/lib/net/blip/nwprog/ -I../../tos/lib/net/blip/shell/ -I../../tos/lib/net/blip/serial/ -I../../tos/lib/net/blip/platform/ -I../../tos/lib/net/blip/icmp/ -I../../tos/lib/net/blip/dhcp/ -I../../tos/platforms/iris -I../../tos/platforms/micaz -I../../tos/platforms/mica -I../../tos/platforms/iris/chips/rf230 -I../../tos/chips/rf230 -I../../tos/lib/rfxlink/layers -I../../tos/lib/rfxlink/util -I../../tos/platforms/iris/chips/at45db -I../../tos/platforms/mica2/chips/at45db -I../../tos/platforms/mica/chips/at45db -I../../tos/chips/at45db -I../../tos/platforms/iris/chips/ds2401 -I../../tos/platforms/mica2/chips/ds2401 -I../../tos/chips/ds2401 -I../../tos/chips/atm1281 -I../../tos/chips/atm1281/adc -I../../tos/chips/atm1281/timer -I../../tos/chips/atm128 -I../../tos/chips/atm128/adc -I../../tos/chips/atm128/pins -I../../tos/chips/atm128/spi -I../../tos/chips/atm128/i2c -I../../tos/chips/atm128/timer -I../../tos/lib/timer -I../../tos/lib/serial -I../../tos/lib/power -I../../tos/lib/diagmsg -mmcu=atmega1281 -fnesc-target=avr -fnesc-no-debug -DPLATFORM_IRIS -Wall -Wshadow --param max-inline-insns-single=100000 -Wno-unused-but-set-variable -Wno-enum-compare -I../../tos/system -I../../tos/types -I../../tos/interfaces -DIDENT_APPNAME=\"PppRouterC\" -DIDENT_USERNAME=\"nelson\" -DIDENT_HOSTNAME=\"nelson-VirtualB\" -DIDENT_USERHASH=0x54e576cfL -DIDENT_TIMESTAMP=0x5c13e928L -DIDENT_UIDHASH=0x2e31c71eL -fnesc-dump=wiring -fnesc-dump='interfaces(!abstract())' -fnesc-dump='referenced(interfacedefs, components)' -fnesc-dumpfile=build/iris/wiring-check.xml PppRouterC.nc -lm  ../../tools/tinyos/c/blip/lib6lowpan/iovec.c ../../tools/tinyos/c/blip/lib6lowpan/in_cksum.c ../../tools/tinyos/c/blip/lib6lowpan/ip_malloc.c ../../tools/tinyos/c/blip/lib6lowpan/utility.c ../../tos/lib/net/blip/table.c
In file included from ../../tos/lib/timer/MuxAlarmMilli32C.nc:47,
                 from ../../tos/lib/ppp/LcpAutomatonC.nc:72,
                 from ../../tos/lib/ppp/LinkControlProtocolC.nc:89,
                 from ../../tos/lib/ppp/PppDaemonC.nc:65,
                 from PppRouterC.nc:16:
In component `MuxAlarmMilli32C_':
../../tos/lib/timer/MuxAlarmMilli32C_.nc:55: component AlarmMilli32C not found
../../tos/lib/timer/MuxAlarmMilli32C_.nc:55: component `AlarmMilli32C' is not generic
../../tos/lib/timer/MuxAlarmMilli32C_.nc:56: no match
../../support/make/Makerules:369: recipe for target 'exe' failed
make: *** [exe] Error 1

*********************************************************************************************************************************************************************************************************************************************************
nelson@nelson-VirtualBox:~/tinyos-main/apps/CoapBlip$ make iris blip coap install,3 mib520,/dev/ttyUSB0
[INFO] creating StorageVolumes.h
tos-sub-tosdir (warning): All expansions of -I%T/lib/app/coap/interfaces/ did not match any directories or files that
exist.
[INFO] compiling CoapBlipC to a iris binary
nescc -o build/iris/main.exe   -Os -DRPL_ROUTING -DRPL_STORING_MODE -I ../../tos/lib/net/rpl -DRPL_OF_0=1 -DRPL_OF_MRH
OF=0 -DIN6_PREFIX=\"fec0::\" -gcc=avr-gcc -Wnesc-all -fnesc-include=tos -fnesc-scheduler=TinySchedulerC,TinySchedulerC
.TaskBasic,TaskBasic,TaskBasic,runTask,postTask -fnesc-cfile=build/iris/app.c -fnesc-separator=__ -DCC2420_HW_ACKNOWLE
DGEMENTS -DCC2420_HW_ADDRESS_RECOGNITION -DRFA1_HARDWARE_ACK -DRFA1_HWACK_64BIT -DRF230_HARDWARE_ACK -DRF230_HWACK_64B
IT -DIEEE154BARE_ENABLED -DPACKET_LINK -DTOSH_DATA_LENGTH=112 -I../../tos/lib/net/ -I../../tos/lib/printf/ -I../../too
ls/tinyos/c/blip/ -I../../tos/lib/net/blip/ -I../../tos/lib/net/blip/interfaces/ -I../../tos/lib/net/blip/nwprog/ -I..
/../tos/lib/net/blip/shell/ -I../../tos/lib/net/blip/serial/ -I../../tos/lib/net/blip/platform/ -I../../tos/lib/net/bl
ip/icmp/ -I../../tos/lib/net/blip/dhcp/ -DBIG_ENDIAN=4321 -DLITTLE_ENDIAN=1234 -DBYTE_ORDER=LITTLE_ENDIAN -DNDEBUG=1 -I../../tos/lib/net/coap/ -I../../tos/lib/net/coap/resources/ -I../../tos/lib/net/coap/resources/IPSO/ -I../../tos/lib/
net/coap/translate/ -I../../tools/tinyos/c/coap -I../../tos/platforms/iris -I../../tos/platforms/micaz -I../../tos/pla
I../../tos/lib/net/coap/ -I../../tos/lib/net/coap/resources/ -I../../tos/lib/net/coap/resources/IPSO/ -I../../tos/lib/net/coap/translate/ -I../../tools/tinyos/c/coap -I../../tos/platforms/iris -I../../tos/platforms/micaz -I../../tos/platforms/mica -I../../tos/platforms/iris/chips/rf230 -I../../tos/chips/rf230 -I../../tos/lib/rfxlink/layers -I../../tos/lib/rfxlink/util -I../../tos/platforms/iris/chips/at45db -I../../tos/platforms/mica2/chips/at45db -I../../tos/platforms/mica/chips/at45db -I../../tos/chips/at45db -I../../tos/platforms/iris/chips/ds2401 -I../../tos/platforms/mica2/chips/ds2401 -I../../tos/chips/ds2401 -I../../tos/chips/atm1281 -I../../tos/chips/atm1281/adc -I../../tos/chips/atm1281/timer -I../../tos/chips/atm128 -I../../tos/chips/atm128/adc -I../../tos/chips/atm128/pins -I../../tos/chips/atm128/spi -I../../tos/chips/atm128/i2c -I../../tos/chips/atm128/timer -I../../tos/lib/timer -I../../tos/lib/serial -I../../tos/lib/power -I../../tos/lib/diagmsg -mmcu=atmega1281 -fnesc-target=avr -fnesc-no-debug -DPLATFORM_IRIS -Wall -Wshadow --param max-inline-insns-single=100000 -Wno-unused-but-set-variable -Wno-enum-compare -Ibuild/iris -I../../tos/system -I../../tos/types -I../../tos/interfaces -DRF230_DEF_CHANNEL=16 -DCOAP_SERVER_ENABLED -DMAX_URI_LENGTH=14 -DMAX_SENSOR_NAME_LENGTH=12 -DCOAP_RESOURCE_LED -DCOAP_MAX_PDU_SIZE=127 -DCOAP_CONTENT_TYPE_PLAIN -DWITHOUT_OBSERVE -DWITHOUT_BLOCK -DWITHOUT_WELLKNOWN -DSHORT_ERROR_RESPONSE -DCOAP_PREACK_TIMEOUT=1000 -DCOAP_CLIENT_PORT=61617L -DCOAP_CLIENT_DEST=\"fec0::100\" -I. -DIDENT_APPNAME=\"CoapBlipC\" -DIDENT_USERNAME=\"nelson\" -DIDENT_HOSTNAME=\"nelson-VirtualB\" -DIDENT_USERHASH=0x54e576cfL -DIDENT_TIMESTAMP=0x5c13e828L -DIDENT_UIDHASH=0x89d84f79L -fnesc-dump=wiring -fnesc-dump='interfaces(!abstract())' -fnesc-dump='referenced(interfacedefs, components)' -fnesc-dumpfile=build/iris/wiring-check.xml CoapBlipC.nc -lm  ../../tools/tinyos/c/blip/lib6lowpan/iovec.c ../../tools/tinyos/c/blip/lib6lowpan/in_cksum.c ../../tools/tinyos/c/blip/lib6lowpan/ip_malloc.c ../../tools/tinyos/c/blip/lib6lowpan/utility.c ../../tos/lib/net/blip/table.c ../../tos/lib/net/coap/tinyos_net.c ../../tools/tinyos/c/coap/async.c ../../tools/tinyos/c/coap/block.c ../../tools/tinyos/c/coap/coap_list.c ../../tools/tinyos/c/coap/coap_debug.c ../../tools/tinyos/c/coap/encode.c ../../tools/tinyos/c/coap/hashkey.c ../../tools/tinyos/c/coap/net.c ../../tools/tinyos/c/coap/option.c ../../tools/tinyos/c/coap/pdu.c ../../tools/tinyos/c/coap/resource.c ../../tools/tinyos/c/coap/str.c ../../tools/tinyos/c/coap/subscribe.c ../../tools/tinyos/c/coap/uri.c
In file included from ../../tools/tinyos/c/coap/option.h:18,
                 from ../../tools/tinyos/c/coap/net.h:44,
                 from CoapBlipP.nc:38:
../../tools/tinyos/c/coap/bits.h:18:23: error: sys/types.h: No such file or directory
In file included from ../../tos/lib/net/coap/LibCoapAdapterC.nc:44,
                 from CoapBlipC.nc:47:
In component `LibCoapAdapterP':
../../tos/lib/net/coap/LibCoapAdapterP.nc: In function `coap_send_impl':
../../tos/lib/net/coap/LibCoapAdapterP.nc:103: warning: passing argument 1 of `UDPServer.sendto' discards `const' from pointer target type
In file included from ../../tos/lib/net/coap/LibCoapAdapterC.nc:56,
                 from CoapBlipC.nc:47:
In component `LocalTimeSecondC':
../../tos/lib/timer/LocalTimeSecondC.nc: At top level:
../../tos/lib/timer/LocalTimeSecondC.nc:40: component CounterSecond32C not found
../../tos/lib/timer/LocalTimeSecondC.nc:42: no match
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/net.h:44,
                 from ../../tos/lib/net/coap/tinyos_net.h:36,
                 from ../../tos/lib/net/coap/tinyos_net.c:33:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/net.h:44,
                 from ../../tools/tinyos/c/coap/async.h:19,
                 from ../../tools/tinyos/c/coap/async.c:22:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/block.h:12,
                 from ../../tools/tinyos/c/coap/block.c:21:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/net.h:44,
                 from ../../tools/tinyos/c/coap/coap_debug.c:32:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
../../tools/tinyos/c/coap/net.c:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/option.c:25:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/pdu.c:34:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/net.h:44,
                 from ../../tools/tinyos/c/coap/resource.c:10:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from ../../tools/tinyos/c/coap/option.h:18:0,
                 from ../../tools/tinyos/c/coap/uri.c:27:
../../tools/tinyos/c/coap/bits.h:18:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
../../support/make/Makerules:369: recipe for target 'exe' failed
make: *** [exe] Error 1

**Comment by cire831** [comment]
The second error from:

> nelson@nelson-VirtualBox:~/tinyos-main/apps/CoapBlip$ make iris blip coap install,3 mib520,/dev/ttyUSB0

yields errors like:

> In file included from ../../tools/tinyos/c/coap/option.h:18,
> from ../../tools/tinyos/c/coap/net.h:44,
> from CoapBlipP.nc:38:
> ../../tools/tinyos/c/coap/bits.h:18:23: error: sys/types.h: No such file or directory

The COAP code uses the host systems types.h.  Your system doesn't apprear to have 'sys/types.h'

I don't have a fix for that.  Any fix should try to adapt to the underlying host system automatically.

**Comment by cire831** [comment]
I don't have a fix for either of these problems.

I don't have avr hardware (in particular the Iris platform).  Nor do I use COAP.   The Iris/AVR code and the COAP code is old and I am not aware of a maintainer.

You could try fixing it yourself.  Other than that I don't have any suggestions.  Sorry.
