### ISSUE TITLE
problems when trying to install packages to install tinyos 

### ISSUE THREAD

**Issue by jabberimaher** [tinyos/tinyos-main#434]
hi
when i try to install packages, there is errors:
root@maher-Lenovo-G50-80:/home/maher# apt-get install openssh-client openssh-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssh-client is already the newest version (1:7.6p1-4ubuntu0.3).
openssh-server is already the newest version (1:7.6p1-4ubuntu0.3).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
msp430-46 : Depends: msp430-binutils-46 but it is not going to be installed
Depends: msp430-gcc-46 but it is not going to be installed
Depends: msp430-libc-46 but it is not going to be installed
Depends: msp430mcu-46 but it is not going to be installed
Depends: tinyos-tools but it is not going to be installed or
tinyos-tools-devel but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
when i launch apt --fix-broken install:
root@maher-Lenovo-G50-80:/home/maher# apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
libde265-0 libftdi1 libgssdp-1.0-3 libgupnp-1.0-4 libgupnp-igd-1.0-4
libjama-java liblilv-0-0 libserd-0-0 libsord-0-0 libsratom-0-0 libssl-doc
libvo-aacenc0 libvo-amrwbenc0 nescc uisp
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
msp430-binutils-46 msp430-gcc-46 msp430-libc-46 msp430mcu-46 nesc
tinyos-tools
The following NEW packages will be installed:
msp430-binutils-46 msp430-gcc-46 msp430-libc-46 msp430mcu-46 nesc
tinyos-tools
0 upgraded, 6 newly installed, 0 to remove and 364 not upgraded.
14 not fully installed or removed.
Need to get 0 B/74.1 MB of archives.
After this operation, 880 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 222833 files and directories currently installed.)
Preparing to unpack .../0-msp430-binutils-46_2.21.1-LTS20120406-tinyprod_amd64.deb ...
Unpacking msp430-binutils-46 (2.21.1-LTS20120406-tinyprod) ...
dpkg: error processing archive /tmp/apt-dpkg-install-lvzLMo/0-msp430-binutils-46_2.21.1-LTS20120406-tinyprod_amd64.deb (--unpack):
trying to overwrite '/usr/msp430/lib/ldscripts/msp430.xbn', which is also in package binutils-msp430 2.22msp20120406-5.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../1-msp430-gcc-46_4.6.3-LTS20120406+20120911-tinyprod_amd64.deb ...
Unpacking msp430-gcc-46 (4.6.3-LTS20120406+20120911-tinyprod) ...
dpkg: error processing archive /tmp/apt-dpkg-install-lvzLMo/1-msp430-gcc-46_4.6.3-LTS20120406+20120911-tinyprod_amd64.deb (--unpack):
trying to overwrite '/usr/lib/gcc/msp430/4.6.3/include-fixed/syslimits.h', which is also in package gcc-msp430 4.6.3mspgcc-20120406-7ubuntu5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../2-msp430-libc-46_20120224-LTS20120406+20120502-tinyprod_amd64.deb ...
.........
may be i need to re-install ubuntu (i use 18.04 version)
best regards

**Comment by cire831** [comment]
something installed the file /usr/lib/gcc/msp430/4.6.3/include-fixed/syslimits.h, try

```dpkg -S /usr/lib/gcc/msp430/4.6.3/include-fixed/syslimits.h```

I don't have that file on my system.  Did you install some 4.6.3 msp430 gcc toolchain from Ubuntu?

I'm using Ubuntu 18.04
