### ISSUE TITLE
How to implement DTLS on Tinyos/TOSSIM

### ISSUE THREAD

**Issue by jabberimaher** [tinyos/tinyos-main#436]
Hi,
Please i would implement DTLS under Tinyos/TOSSIM, then i want to measure the consumed energy and the time execution by the node.
best regards

**Comment by cire831** [comment]
what exactly are you asking?

what is DTLS?

Generally, people need to figure out how to implement things themselves.  The community can help, but you will need to figure most things out yourself.

this kind of request is more apporpriate for tinyos-help@millennium.berkeley.edu

you submitted an issue which is typically used for bug and feature tracking.
