### ISSUE TITLE
Issue compiling 'make micaz sim'

### ISSUE THREAD

**Issue by namyamalik** [tinyos/tinyos-main#440]
I am trying to simulate the Blink application within tinyOS with the command `make micaz sim`. However, I am running into some issue with syntax errors. I read about a similar issue (https://github.com/tinyos/tinyos-main/issues/432) but it was never resolved. Fyi I am running tinyOS on my school's Linux server (not a virtual machine). I am stuck on this, so any help is appreciated.

Below is the output when I try to build the Blink application:

`[INFO] placing object files in simbuild/micaz  
[INFO] writing XML schema to app.xml  
[INFO] compiling BlinkAppC to object file sim.o  
nescc -c -shared -fPIC -o simbuild/micaz/sim.o -g -O0 -gcc=gcc -Wnesc-all -fnesc-include=tos -fnesc-scheduler=TinySchedulerC,TinySchedulerC.TaskBasic,TaskBasic,TaskBasic,runTask,postTask -fnesc-cfile=simbuild/micaz/app.c -fnesc-separator=__ -DTOSSIM -fnesc-nido-tosnodes=1000 -fnesc-simulate -fnesc-nido-motenumber=sim_node\(\) -fnesc-gcc=gcc -I../../tos/lib/tossim -I../../tos/platforms/micaz/sim -I../../tos/platforms/micaz -I../../tos/platforms/mica/sim -I../../tos/platforms/mica -I../../tos/platforms/micaz/chips/cc2420/sim -I../../tos/platforms/micaz/chips/cc2420 -I../../tos/chips/cc2420/sim -I../../tos/chips/cc2420 -I../../tos/chips/cc2420/alarm -I../../tos/chips/cc2420/control/sim -I../../tos/chips/cc2420/control -I../../tos/chips/cc2420/csma/sim -I../../tos/chips/cc2420/csma -I../../tos/chips/cc2420/interfaces/sim -I../../tos/chips/cc2420/interfaces -I../../tos/chips/cc2420/link/sim -I../../tos/chips/cc2420/link -I../../tos/chips/cc2420/lowpan/sim -I../../tos/chips/cc2420/lowpan -I../../tos/chips/cc2420/lpl -I../../tos/chips/cc2420/packet/sim -I../../tos/chips/cc2420/packet -I../../tos/chips/cc2420/receive/sim -I../../tos/chips/cc2420/receive -I../../tos/chips/cc2420/spi -I../../tos/chips/cc2420/transmit -I../../tos/chips/cc2420/unique/sim -I../../tos/chips/cc2420/unique -I../../tos/platforms/mica2/chips/at45db -I../../tos/platforms/mica/chips/at45db -I../../tos/chips/at45db -I../../tos/chips/atm128/sim -I../../tos/chips/atm128 -I../../tos/chips/atm128/adc -I../../tos/chips/atm128/pins/sim -I../../tos/chips/atm128/pins -I../../tos/chips/atm128/spi/sim -I../../tos/chips/atm128/spi -I../../tos/chips/atm128/timer/sim -I../../tos/chips/atm128/timer -I../../tos/lib/power -I../../tos/lib/timer -I../../tos/lib/serial -fnesc-no-debug -DPLATFORM_MICAZ -Wall -Wshadow -finline-limit=100000 -I../../tos/system -I../../tos/types -I../../tos/interfaces -DIDENT_APPNAME=\"BlinkAppC\" -DIDENT_USERNAME=\"nmalik\" -DIDENT_HOSTNAME=\"flume.cs.dartmo\" -DIDENT_USERHASH=0x48b3dcceL -DIDENT_TIMESTAMP=0x5ef8251eL -DIDENT_UIDHASH=0x7d629717L -Wno-nesc-data-race BlinkAppC.nc   -fnesc-dump=components -fnesc-dump=variables -fnesc-dump=constants -fnesc-dump=typedefs -fnesc-dump=interfacedefs -fnesc-dump=tags -fnesc-dumpfile=app.xml
In file included from /usr/include/math.h:420,
                 from ../../tos/lib/tossim/tos.h:59:
/usr/include/bits/mathcalls-helper-functions.h:21: syntax error before `__value'
/usr/include/bits/mathcalls-helper-functions.h:25: syntax error before `__value'
/usr/include/bits/mathcalls-helper-functions.h:30: syntax error before `__value'
/usr/include/bits/mathcalls-helper-functions.h:33: syntax error before `__value'
/usr/include/bits/mathcalls-helper-functions.h:36: syntax error before `__value'
/usr/include/bits/mathcalls-helper-functions.h:39: syntax error before `__x'
/usr/include/bits/mathcalls-helper-functions.h:42: syntax error before `__value'
make: *** [../../support/make/extras/sim.extra:70: sim-exe] Error 1`

**Comment by cire831** [comment]
the simulator hasn't been supported for years.

but that error looks like it is a tool chain problem.  I've seen similar errors occur when we've updated to using a newer version of the compiler.

you might try compiling with verbose turned on (I beleive "-v") that might give you a clue as to what to look at.

Other than than, sorry, you are on your own.
