### ISSUE TITLE
Meet problem in ~/top/tinyos-main/tinyos-2.x/apps/tutorials/RssiDemo

### ISSUE THREAD

**Issue by Hangch-yx** [tinyos/tinyos-main#444]
I installed tinyos-main following the 00c_Setting_Up_Debian_Development
And accomplished the test successfully in "~/top/tinyos-main/tinyos-2.x/apps/Blink" 
However when I input the command "sudo make" in the Terminal ( working directory is ~/top/tinyos-main/tinyos-2.x/apps/tutorials/RssiDemo/java), there are some errors.

AND I find there is no "~/top/tinyos-main/tinyos-2.x/support/sdk" in tinyos-main( there is only one directory named "make" in "~/top/tinyos-main/tinyos-2.x/support"   BUT the fourth step(Set up build environment settings) in  "00c_Setting_Up_Debian_Development"  set the CLASSPATH=.:$TR/support/sdk/java/tinyos.jar. 

I felt very confused because there is no "tinyos.jar" in tinyos-main. and I want to know Whether It caused the errors I met.

the errors:work@work-OptiPlex-3046:~/top/tinyos-main/tinyos-2.x/apps/tutorials/RssiDemo/java$ sudo make
javac RssiDemo.java RssiMsg.java
RssiDemo.java:53: error: cannot find symbol
public class RssiDemo implements MessageListener {
                                 ^
  symbol: class MessageListener
RssiDemo.java:55: error: cannot find symbol
  private MoteIF moteIF;
          ^
  symbol:   class MoteIF
  location: class RssiDemo
RssiDemo.java:57: error: cannot find symbol
  public RssiDemo(MoteIF moteIF) {
                  ^
  symbol:   class MoteIF
  location: class RssiDemo
RssiDemo.java:62: error: cannot find symbol
  public void messageReceived(int to, Message message) {
                                      ^
  symbol:   class Message
  location: class RssiDemo
RssiDemo.java:49: error: package net.tinyos.message does not exist
import net.tinyos.message.*;
^
RssiDemo.java:50: error: package net.tinyos.packet does not exist
import net.tinyos.packet.*;
^
RssiDemo.java:51: error: package net.tinyos.util does not exist
import net.tinyos.util.*;
^
RssiMsg.java:7: error: package net.tinyos.message does not exist
public class RssiMsg extends net.tinyos.message.Message {
                                               ^
RssiMsg.java:67: error: package net.tinyos.message does not exist
    public RssiMsg(net.tinyos.message.Message msg, int base_offset) {
                                     ^
RssiMsg.java:76: error: package net.tinyos.message does not exist
    public RssiMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
                                     ^
RssiDemo.java:87: error: cannot find symbol
    PhoenixSource phoenix;
    ^
  symbol:   class PhoenixSource
  location: class RssiDemo
RssiDemo.java:90: error: cannot find symbol
      phoenix = BuildSource.makePhoenix(PrintStreamMessenger.err);
                                        ^
  symbol:   variable PrintStreamMessenger
  location: class RssiDemo
RssiDemo.java:90: error: cannot find symbol
      phoenix = BuildSource.makePhoenix(PrintStreamMessenger.err);
                ^
  symbol:   variable BuildSource
  location: class RssiDemo
RssiDemo.java:93: error: cannot find symbol
      phoenix = BuildSource.makePhoenix(source, PrintStreamMessenger.err);
                                                ^
  symbol:   variable PrintStreamMessenger
  location: class RssiDemo
RssiDemo.java:93: error: cannot find symbol
      phoenix = BuildSource.makePhoenix(source, PrintStreamMessenger.err);
                ^
  symbol:   variable BuildSource
  location: class RssiDemo
RssiDemo.java:96: error: cannot find symbol
    MoteIF mif = new MoteIF(phoenix);
    ^
  symbol:   class MoteIF
  location: class RssiDemo
RssiDemo.java:96: error: cannot find symbol
    MoteIF mif = new MoteIF(phoenix);
                     ^
  symbol:   class MoteIF
  location: class RssiDemo
RssiMsg.java:18: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:24: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:33: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:42: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:51: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:60: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:69: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:78: error: cannot find symbol
        amTypeSet(AM_TYPE);
        ^
  symbol:   method amTypeSet(int)
  location: class RssiMsg
RssiMsg.java:134: error: cannot find symbol
        return (short)getSIntBEElement(offsetBits_rssi(), 16);
                      ^
  symbol:   method getSIntBEElement(int,int)
  location: class RssiMsg
RssiMsg.java:141: error: cannot find symbol
        setSIntBEElement(offsetBits_rssi(), 16, value);
        ^
  symbol:   method setSIntBEElement(int,int,short)
  location: class RssiMsg
27 errors
Makefile:7: recipe for target 'RssiDemo.class' failed
make: *** [RssiDemo.class] Error 1

**Comment by cire831** [comment]
why are you doing "sudo make"  that will run make as root which isn't a good idea.

I don't remember how the tinyos-tools.jar file is built.  I don't use Java.  Sorry I can't help you.
